### ISSUE TITLE
Instructor Review - Week 14

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [SSAJJALA/CreditDebitRequest#6]
- [x] Can you check your time log formatting? When viewing it on github it runs together and is hard to read.
- [x] Missing .gitignore so some workspace files are checked into version control
- [x] Remember it is a best practice to call the no-arg constructor from the overridden constructors
- [x] Work to break down long methods with nested logic into smaller, more maintainable methods. For example: routeCDMR() 
- [x] Consider constants to replace hard-coded strings - servlets have opportunity here
- [x] Be sure to close session after opening session in your daos - many of the get-type methods leave the session open.
- [x] Consider a generic dao to reduce the redundancy in  the daos. 
- [x] Watch for copy/pasted/repeated lines of code. Example: CDMRDetailsServlet.doGet() has:} else if (request.getParameter("btn_exit") != null) {
            logger.info("Exiting cdmr request");
            session.removeAttribute("cdmr");
            session.removeAttribute("taskDetails");
            session.removeAttribute("message");
            buttonAction = "Exit";
        } else if (request.getParameter("btn_message") != null) {
            logger.info("directing to index page");
            session.removeAttribute("cdmr");
            session.removeAttribute("taskDetails");
            session.removeAttribute("message");
            buttonAction = "Message";
- [x] unit testing could be improved. Also consider unit tests for your utility classes.
- [x] Good use of logging, check for a few e.printStackTrace(); that snuck in there - use error logging instead.
- [x] Javadoc is good for the most part but I did notice some missing in the Data package for example. 
- [x] Good use of templating, jstl in your jsps. 
- [x] Good separation of code into appropriate packages
- [x] Looks like this is up on digital ocean - good work!

**Comment by SSAJJALA** [comment]
Almost all of the above open items are fixed except making the DAO classes more generic. I am working on it to fix.

**Comment by SSAJJALA** [comment]
Customer Lookup web service is updated with more exception handling and client is also modified to handle those exceptins

**Comment by SSAJJALA** [comment]
Generaic DAO (Abstract) and Concrete implementation DAOs are built and pushed the code to git
